// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "curator-backend",
    "version": "1"
  },
  "paths": {
    "/registration": {
      "post": {
        "summary": "user-createUser",
        "description": "",
        "operationId": "user-createUser.post.registration",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/userDetail": {
      "get": {
        "summary": "user-detail",
        "description": "",
        "operationId": "user-detail.get.userDetail",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/loginUser": {
      "post": {
        "summary": "user-loginUser",
        "description": "",
        "operationId": "user-loginUser.post.loginUser",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/sms": {
      "get": {
        "summary": "user-sms",
        "description": "",
        "operationId": "user-sms.get.sms",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/usercategory": {
      "get": {
        "summary": "user-category",
        "description": "",
        "operationId": "user-category.get.usercategory",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getCategories": {
      "get": {
        "summary": "categories-getCategories",
        "description": "",
        "operationId": "categories-getCategories.get.getCategories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/categories/{id}": {
      "delete": {
        "summary": "deleteCategories",
        "description": "",
        "operationId": "deleteCategories.delete.categories/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/categories": {
      "post": {
        "summary": "createCategories",
        "description": "",
        "operationId": "createCategories.post.categories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/question/{id}": {
      "get": {
        "summary": "getQuestion",
        "description": "",
        "operationId": "getQuestion.get.question/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deleteQuestion",
        "description": "",
        "operationId": "deleteQuestion.delete.question/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/question": {
      "post": {
        "summary": "createQuestion",
        "description": "",
        "operationId": "createQuestion.post.question",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/answer": {
      "post": {
        "summary": "saveAnswer",
        "description": "",
        "operationId": "saveAnswer.post.answer",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/comments/{id}": {
      "get": {
        "summary": "getAnswers",
        "description": "",
        "operationId": "getAnswers.get.comments/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-answers": {
      "get": {
        "summary": "getAllAnswers",
        "description": "",
        "operationId": "getAllAnswers.get.get-answers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-answers/{id}": {
      "get": {
        "summary": "getQuestionAnswers",
        "description": "",
        "operationId": "getQuestionAnswers.get.get-answers/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/get-user-score/{id}": {
      "get": {
        "summary": "getUserScore",
        "description": "",
        "operationId": "getUserScore.get.get-user-score/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/answer/{id}": {
      "delete": {
        "summary": "deleteAnswers",
        "description": "",
        "operationId": "deleteAnswers.delete.answer/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/comments": {
      "post": {
        "summary": "saveComments",
        "description": "",
        "operationId": "saveComments.post.comments",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/approve-answer": {
      "post": {
        "summary": "approveAnswer",
        "description": "",
        "operationId": "approveAnswer.post.approve-answer",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};